import type { Copy } from './en';

export const de = {
  nav: { studio: 'Das Studio', downloads: 'Downloads', guide: 'Anleitung', source: 'Quellcode' },
  mainNavigation: 'Hauptnavigation',
  languageLabel: 'DE, Auf Deutsch lesen',
  footerNavigation: 'Weitere Informationen',
  skip: 'Zum Inhalt springen',
  home: 'garret Startseite',
  themeToggle: { light: 'Zum hellen Modus wechseln', dark: 'Zum dunklen Modus wechseln' },
  zoom: 'Vergrößern', fit: 'Einpassen',
  close: 'Schließen',
  enlarge: 'Screenshot ansehen',
  imageLoading: 'Screenshot wird geladen...',
  imageError: 'Der Screenshot konnte nicht geladen werden. Versuche, das Originalbild zu öffnen.',
  imageRegion: 'Screenshot. Nach dem Vergrößern scrollbar.',
  zoomHint: 'Wähle Vergrößern, um Details zu lesen.',
  panHint: 'Scrolle im vergrößerten Bild. Um die Pfeiltasten zu nutzen, drücke Tab, bis du das Bild erreichst.',
  allDownloads: 'Alle Downloads ansehen',
  original: 'Originalbild öffnen',
  newTab: 'öffnet einen neuen Tab',
  footer: {
    creator: 'Von Iulian Dita',
    about: 'Über garret & Datenschutz', credits: 'Bildnachweise', issues: 'Problem melden',
    support: 'garret unterstützen', license: 'Freie Software. GPL-3.0-or-later.',
  },
  hero: {
    androidNote: 'Die Android-App bietet eine Bibliothek und einen Szeneneditor mit weniger Funktionen als auf dem Desktop. In dieser Version kannst du keine Bücher importieren oder exportieren, keine verschlüsselten Archive erstellen und keine Bücher automatisch synchronisieren. Deinstallieren oder Löschen der App-Daten löscht die Bücher.',
    getFor: 'garret für {platform} laden', alpha: 'Frühe Alpha-Version.', alphaGuide: 'Lies die Anleitung, bevor du damit wichtige Texte schreibst.',
    title: 'Ein Schreibstudio für den ganzen Roman.',
    description: 'Dein Manuskript, deine Figuren, Recherche und Überarbeitung an einem Ort. Schreibe offline und ohne Konto. Alle Funktionen sind kostenlos.',
    download: 'garret herunterladen', explore: 'Das Studio entdecken',
    caption: 'Der Desktop-Editor mit englischer Oberfläche. Dein Manuskript und der Rest deines Buches in Reichweite.',
    alt: 'garret-Manuskripteditor mit Kapitelnavigation und Schreibwerkzeugen',
    darkAlt: 'garret-Editor im dunklen Modus mit Stolz und Vorurteil und Kapitelnavigation',
  },
  studio: {
    write: { title: 'Platz für deine Worte.', description: 'Schreibe in Szenen und Kapiteln. Suche im ganzen Buch, hinterlasse Kommentare oder kehre zu einer früheren Szenenfassung zurück. Im Fokusmodus gehört der Platz dem Manuskript.' },
    organize: { title: 'Behalte deine Geschichte im Blick.', description: 'Baue deine Figurenkartei und Story-Bibel auf. Halte Zusammenfassungen und Recherche griffbereit. Ordne Ereignisse auf der Zeitleiste und springe von dort zurück zur Szene.', alt: 'Beispielhafte Alice-Ereignisse auf der garret-Zeitleiste', caption: 'Eine Zeitleiste, die mit dem Manuskript verbunden bleibt.' },
    revise: { title: 'Arbeite an der nächsten Fassung.', description: 'Tausche DOCX-Dokumente mit deinem Lektorat aus. Sieh, von wem ein Änderungsvorschlag stammt, und nimm ihn an oder lehne ihn ab. Kommentare, Überarbeitungsrunden und Aufgaben bleiben beim Buch.', alt: 'Änderungsvorschläge mit Angabe, von wem sie stammen, neben dem Manuskript in garret', caption: 'Rückmeldungen aus dem Lektorat bleiben beim Manuskript.' },
    prepare: { title: 'Vom Manuskript zum Buch.', description: 'Exportiere Markdown, DOCX oder EPUB. Lege Cover, Pseudonyme, Vor- und Nachspann sowie das Buchdesign fest. Unter Linux kannst du auch PDF-Korrekturabzüge erstellen.', alt: 'Buchdesign und EPUB-Export in garret', caption: 'Bereite ein EPUB direkt in deinem Schreibstudio vor.' },
  },
  ownership: {
    title: 'Dein Buch bleibt bei dir.',
    description: 'Bücher liegen auf deinem eigenen Datenträger. Schreibe ohne Internetverbindung und ohne Konto. Alle Funktionen sind kostenlos, der Quellcode ist offen.',
    backup: 'Arbeitsmanuskripte sind nicht verschlüsselt. Speichere sie außerhalb von Cloud-Ordnern. Erstelle verschlüsselte Archive manuell, bewahre den Wiederherstellungsschlüssel getrennt auf und prüfe dein gespeichertes Archiv.',
    link: 'Eine Sicherungskopie anlegen',
  },
  android: {
    download: 'garret für Android laden',
    title: 'Ein kleineres Studio für dein Smartphone.',
    description: 'Android bietet eine Bibliothek und einen Szeneneditor für unterwegs, mit weniger Funktionen als auf dem Desktop. In dieser Version kannst du keine Bücher importieren oder exportieren, keine verschlüsselten Archive erstellen und keine Bücher automatisch synchronisieren. Deinstallieren oder Löschen der App-Daten löscht die Bücher; bewahre eine unabhängige Kopie wichtiger Texte auf.',
    alt: 'Android-Szeneneditor von garret mit Manuskripttext',
    darkAlt: 'Android-Szeneneditor von garret im dunklen Modus mit Dracula',
    caption: 'Der Android-Szeneneditor mit englischer Oberfläche.',
  },
  highlights: {
    title: 'Mehr Platz für deinen Roman.',
    write: { title: 'Raum zum Schreiben', description: 'Ein konzentrierter Editor, Szenen und Kapitel. Deine Worte bleiben auf deinem eigenen Datenträger.' },
    story: { title: 'Die ganze Geschichte an einem Ort', description: 'Figuren, Recherche und Planung bleiben beim Manuskript, ohne einen Stapel getrennter Dateien.' },
    finish: { title: 'Ein Weg zum fertigen Buch', description: 'Überarbeite mit deinem Lektorat, gestalte das Buch und exportiere es, wenn du bereit bist.' },
  },
  testimonial: {
    label: 'Ein erster Eindruck',
    attribution: 'George Patterson (englisches Original)',
  },
  browse: {
    title: 'Weitere Werkzeuge, wenn du sie brauchst.',
    description: 'Entdecke das Desktop-Studio in deinem eigenen Tempo. Die Screenshots zeigen die englische Oberfläche.',
    previous: 'Vorheriges Thema', next: 'Nächstes Thema',
    fallbackHint: 'Wähle ein Thema oder wische.',
    position: 'Thema', of: 'von', hint: 'Wähle ein Thema, nutze die Pfeile oder wische.',
  },
  features: {
    recoveryTitle: 'Finde zurück zu deiner Arbeit.',
    region: 'Desktop-Funktionen',
    navigate: 'Desktop-Funktionen entdecken',
    writing: 'Schreiben', organizing: 'Geschichte & Recherche', revision: 'Überarbeitung', publishing: 'Veröffentlichen', recovery: 'Eigene Daten & Wiederherstellung',
    focus: { title: 'Konzentriere dich auf eine Szene', description: 'Arbeite in Teilen, Kapiteln und Szenen. Im Fokusmodus werden die übrigen Werkzeuge beim Schreiben ausgeblendet.' },
    formatting: { title: 'Formatiere beim Schreiben', description: 'Formatierungswerkzeuge erscheinen bei deiner Textauswahl. Mit Rückgängig und Wiederholen kannst du einen Satz neu angehen.' },
    search: { title: 'Durchsuche das ganze Buch', description: 'Finde Namen oder Formulierungen im gesamten Manuskript und springe zur Textstelle.' },
    preferences: { title: 'Schreibe auf deine Weise', description: 'Wähle den hellen oder dunklen Modus, Englisch oder Deutsch und dein eigenes tägliches Wortziel. Zeige Wortzahlen für Szenen, Kapitel oder Teile nach Bedarf an.' },
    cast: { title: 'Lerne deine Figuren kennen', description: 'Halte Figurenprofile, andere Namen, Bilder und Beschreibungen neben deinem Manuskript griffbereit.' },
    bible: { title: 'Führe eine Story-Bibel', description: 'Gib deiner Welt, Kontinuitätsregeln und Hintergrundnotizen einen Platz im Buch.' },
    synopses: { title: 'Fasse jede Szene zusammen', description: 'Schreibe Szenenzusammenfassungen und lies sie neben dem Manuskript oder in der Gliederung.' },
    research: { title: 'Halte Recherche griffbereit', description: 'Verknüpfe Recherchedateien mit deinem Buch, damit Quellen beim Schreiben in Reichweite bleiben.' },
    outline: { title: 'Sieh die Form deiner Geschichte', description: 'Ordne Kapitel und Szenen in einer Gliederungstabelle oder als Karten mit ihren Zusammenfassungen.' },
    appearances: { title: 'Verfolge Figuren durch die Szenen', description: 'Sieh, in welchen Szenen jede Figur vorkommt, und folge verknüpften Ereignissen auf der Zeitleiste.' },
    review: { title: 'Arbeite mit deinem Lektorat', description: 'Sende deinem Lektorat ein DOCX-Dokument und importiere die Änderungsvorschläge. Du siehst, von wem jeder Vorschlag stammt.' },
    comments: { title: 'Behalte Kommentare im Kontext', description: 'Halte Kommentare direkt bei der Textstelle und markiere sie als erledigt, wenn sie geklärt sind.' },
    history: { title: 'Vergleiche frühere Fassungen', description: 'Schau dir frühere Fassungen deiner Szenen an, vergleiche den Text und speichere Momentaufnahmen mit eigenen Namen.' },
    revisions: { title: 'Plane deine nächste Überarbeitung', description: 'Halte Aufgaben bei deinem Buch fest und ordne sie in Überarbeitungsrunden.' },
    export: { title: 'Wähle ein passendes Format', description: 'Exportiere Markdown, DOCX oder EPUB für den nächsten Schritt mit deinem Buch.' },
    design: { title: 'Bereite das vollständige Buch vor', description: 'Lege Buchdesign, Vor- und Nachspann sowie Cover vor dem Export fest.' },
    authors: { title: 'Schreibe unter einem Pseudonym', description: 'Halte deine Pseudonyme und Veröffentlichungsdetails zusammen.' },
    proof: { title: 'Prüfe einen Korrekturabzug', description: 'Unter Linux kannst du das Buchlayout vorab ansehen und vor der Veröffentlichung einen PDF-Korrekturabzug exportieren.' },
    archives: { title: 'Speichere eine verschlüsselte Sicherung', description: 'Erstelle ein verschlüsseltes Archiv manuell, prüfe es mit deinem Wiederherstellungsschlüssel und stelle es bei Bedarf als separates Buch wieder her.' },
    mirror: { title: 'Behalte eine lesbare Kopie', description: 'Halte deinen Text in einem lesbaren Ordner neben deinem Buch bereit. Diese Kopie ist unverschlüsselt und keine vollständige Sicherung.' },
    salvage: { title: 'Rette, was sich retten lässt', description: 'Lokale Wiederherstellungskopien, frühere Szenenfassungen und Rettungswerkzeuge helfen dir, deine Arbeit wiederzufinden.' },
    series: { title: 'Arbeite an einer Reihe', description: 'Ordne Bücher zu einer Reihe, während jedes Manuskript auf deinem eigenen Datenträger bleibt.' },
    reports: { title: 'Behalte deine Schreibarbeit im Blick', description: 'Sieh Statistiken zu deinem Buch und Berichte zu Schreibstil und Konsistenz. Sitzungsstatistiken sind optional. All das bleibt auf deinem Gerät.' },
    lock: { title: 'Verbirg die App, wenn du weggehst', description: 'Auf unterstützten Desktop-Versionen verbirgt eine optionale PIN-Sperre garret, wenn du weggehst. Deine Manuskriptdateien bleiben unverschlüsselt.' },
    formattingAlt: 'Formatierungswerkzeuge neben ausgewähltem Text aus Alice im Wunderland in garret',
    formattingCaption: 'Formatierungswerkzeuge bleiben bei deiner Textauswahl.',
    cardsAlt: 'garret-Gliederungskarten mit Kapiteln, Szenen und Zusammenfassungen',
    cardsCaption: 'Behalte Struktur und Figuren neben dem Manuskript im Blick.',
    castAlt: 'garret im dunklen Modus mit einem Dracula-Figurenprofil neben dem Manuskript',
    commentsAlt: 'garret im dunklen Modus mit einem beispielhaften Lektoratskommentar neben ausgewähltem Text aus Stolz und Vorurteil',
    historyAlt: 'garret-Szenenverlauf mit einem Vergleich zwischen einer früheren Fassung und dem aktuellen Text',
    historyCaption: 'Vergleiche frühere Formulierungen im Szenenverlauf. Hier mit beispielhaften Überarbeitungen.',
  },
} satisfies Copy;
