import type { Copy } from './en';

export const de = {
  nav: { studio: 'Das Studio', downloads: 'Downloads', guide: 'Anleitung', source: 'Quellcode' },
  mainNavigation: 'Hauptnavigation',
  languageLabel: 'DE, Auf Deutsch lesen',
  footerNavigation: 'Weitere Informationen',
  skip: 'Zum Inhalt springen',
  home: 'garret Startseite',
  themeToggle: { light: 'Zum hellen Modus wechseln', dark: 'Zum dunklen Modus wechseln' },
  zoom: 'Vergrößern', fit: 'Einpassen',
  close: 'Schließen',
  enlarge: 'Screenshot ansehen',
  imageLoading: 'Screenshot wird geladen...',
  imageError: 'Der Screenshot konnte nicht geladen werden. Versuche, das Originalbild zu öffnen.',
  imageRegion: 'Screenshot, vergrößert scrollbar',
  zoomHint: 'Wähle Vergrößern, um Details zu lesen.',
  panHint: 'Scrolle im vergrößerten Bild. Für die Pfeiltasten drücke Tab, bis das Bild den Fokus hat.',
  allDownloads: 'Alle Downloads ansehen',
  original: 'Originalbild öffnen',
  newTab: 'öffnet einen neuen Tab',
  footer: {
    creator: 'Von Iulian Dita',
    about: 'Über garret & Datenschutz', credits: 'Bildnachweise', issues: 'Problem melden',
    support: 'garret unterstützen', license: 'Freie Software. GPL-3.0-or-later.',
  },
  hero: {
    androidNote: 'Android bietet eine kleinere Bibliothek und einen Szeneneditor. Noch kein Import/Export oder verschlüsseltes Archiv; Deinstallieren oder Löschen der App-Daten löscht die Bücher.',
    getFor: 'garret für {platform} laden', alpha: 'Frühe Alpha-Version.', alphaGuide: 'Lies die Anleitung, bevor du damit wichtige Texte schreibst.',
    title: 'Ein Schreibstudio für das ganze Buch.',
    description: 'Manuskript, Figuren, Recherche und Überarbeitung für deinen Roman. Funktioniert offline. Ohne Konto. Alle Funktionen sind kostenlos.',
    download: 'garret herunterladen', explore: 'Das Studio entdecken',
    caption: 'Der Desktop-Editor mit englischer Oberfläche. Dein Manuskript und der Rest deines Buches in Reichweite.',
    alt: 'garret-Manuskripteditor mit Kapitelnavigation und Schreibwerkzeugen',
    darkAlt: 'garret-Editor im dunklen Modus mit einem Dracula-Manuskript und Kapitelnavigation',
  },
  studio: {
    write: { title: 'Platz für deine Worte.', description: 'Schreibe in Szenen und Kapiteln. Suche im ganzen Buch, hinterlasse Kommentare oder kehre zu einer früheren Szenenfassung zurück. Im Fokusmodus gehört der Platz dem Manuskript.' },
    organize: { title: 'Behalte deine Geschichte im Blick.', description: 'Baue deine Figurenkartei und Story-Bibel auf. Halte Zusammenfassungen und Recherche griffbereit. Ordne Ereignisse auf der Zeitleiste und springe von dort zurück zur Szene.', alt: 'Dracula-Ereignisse auf Figuren- und Handlungssträngen in der garret-Zeitleiste', caption: 'Eine Zeitleiste, die mit dem Manuskript verbunden bleibt.' },
    revise: { title: 'Arbeite an der nächsten Fassung.', description: 'Tausche DOCX-Dokumente mit deinem Lektorat aus. Sieh, von wem ein Änderungsvorschlag stammt, und nimm ihn an oder lehne ihn ab. Kommentare, Überarbeitungsrunden und Aufgaben bleiben beim Buch.', alt: 'Zugeordnete Änderungsvorschläge neben dem Manuskript in garret', caption: 'Änderungsvorschläge mit Urheber und Kontext.' },
    prepare: { title: 'Vom Manuskript zum Buch.', description: 'Exportiere Markdown, DOCX oder EPUB. Lege Cover, Pseudonyme, Vor- und Nachspann sowie das Buchdesign fest. Unter Linux kannst du auch PDF-Korrekturabzüge erstellen.', alt: 'Buchdesign und EPUB-Export in garret', caption: 'Bereite ein EPUB direkt in deinem Schreibstudio vor.' },
  },
  ownership: {
    title: 'Dein Buch bleibt bei dir.',
    description: 'Bücher liegen auf deinem eigenen Datenträger. Schreibe ohne Internetverbindung und ohne Konto. Alle Funktionen sind kostenlos, der Quellcode ist offen.',
    backup: 'Arbeitsmanuskripte sind nicht verschlüsselt. Speichere sie außerhalb von Cloud-Ordnern. Erstelle verschlüsselte Archive manuell, bewahre den Wiederherstellungsschlüssel getrennt auf und prüfe dein gespeichertes Archiv.',
    link: 'Eine Sicherungskopie anlegen',
  },
  android: {
    download: 'garret für Android laden',
    title: 'Ein kleineres Studio für dein Smartphone.',
    description: 'Android bietet eine Bibliothek und einen Szeneneditor für unterwegs, mit weniger Funktionen und ohne automatische Synchronisierung. Import/Export und verschlüsselte Archive fehlen noch. Deinstallieren oder Löschen der App-Daten löscht die Bücher; bewahre eine unabhängige Kopie wichtiger Texte auf.',
    alt: 'Android-Szeneneditor von garret mit Manuskripttext',
    darkAlt: 'Android-Szeneneditor von garret im dunklen Modus mit Dracula',
    caption: 'Der Android-Szeneneditor.',
  },
  highlights: {
    title: 'Mehr Platz für dein Buch.',
    write: { title: 'Raum zum Schreiben', description: 'Ein konzentrierter Editor, Szenen und Kapitel. Deine Worte bleiben auf deinem eigenen Datenträger.' },
    story: { title: 'Die ganze Geschichte an einem Ort', description: 'Figuren, Recherche und Planung bleiben beim Manuskript, ohne einen Stapel getrennter Dateien.' },
    finish: { title: 'Ein Weg zum fertigen Buch', description: 'Überarbeite mit deinem Lektorat, gestalte das Buch und exportiere es, wenn du bereit bist.' },
  },
  testimonial: {
    label: 'Der erste Eindruck eines Autors',
    attribution: 'George Patterson (englisches Original)',
  },
  browse: {
    title: 'Weitere Werkzeuge, wenn du sie brauchst.',
    description: 'Entdecke das Desktop-Studio in deinem eigenen Tempo. Die Screenshots zeigen die englische Oberfläche.',
    previous: 'Vorherige Funktionsgruppe', next: 'Nächste Funktionsgruppe',
    fallbackHint: 'Wähle ein Kapitel oder wische.',
    position: 'Funktionsgruppe', of: 'von', hint: 'Wähle ein Kapitel, nutze die Pfeile oder wische.',
  },
  features: {
    recoveryTitle: 'Finde zurück zu deiner Arbeit.',
    region: 'Studio-Kapitel',
    navigate: 'Desktop-Funktionen entdecken',
    writing: 'Schreiben', organizing: 'Geschichte & Recherche', revision: 'Überarbeitung', publishing: 'Veröffentlichen', recovery: 'Eigene Daten & Wiederherstellung',
    focus: { title: 'Konzentriere dich auf eine Szene', description: 'Arbeite in Teilen, Kapiteln und Szenen. Im Fokusmodus werden die übrigen Werkzeuge beim Schreiben ausgeblendet.' },
    formatting: { title: 'Formatiere beim Schreiben', description: 'Formatierungswerkzeuge erscheinen bei deiner Textauswahl. Mit Rückgängig und Wiederholen kannst du einen Satz neu angehen.' },
    search: { title: 'Durchsuche das ganze Buch', description: 'Finde Namen oder Formulierungen im gesamten Manuskript und springe zur Textstelle.' },
    preferences: { title: 'Schreibe auf deine Weise', description: 'Wähle den hellen oder dunklen Modus, Englisch oder Deutsch und passe Schreib- und Navigationseinstellungen an.' },
    cast: { title: 'Lerne deine Figuren kennen', description: 'Halte Figurenprofile, Aliasse, Bilder und Beschreibungen neben dem Manuskript griffbereit.' },
    bible: { title: 'Führe eine Story-Bibel', description: 'Gib deiner Welt, Kontinuitätsregeln und Hintergrundnotizen einen Platz im Buch.' },
    synopses: { title: 'Fasse jede Szene zusammen', description: 'Schreibe Szenenzusammenfassungen und lies sie neben dem Manuskript oder in der Gliederung.' },
    research: { title: 'Halte Recherche griffbereit', description: 'Verknüpfe Recherchedateien mit deinem Buch, damit Quellen beim Schreiben in Reichweite bleiben.' },
    outline: { title: 'Sieh die Form deiner Geschichte', description: 'Ordne Kapitel und Szenen in einer Gliederungstabelle oder als Karten mit ihren Zusammenfassungen.' },
    appearances: { title: 'Verfolge Figuren durch die Szenen', description: 'Die Auftrittsübersicht zeigt, wo Figuren in der Geschichte vorkommen. Die Zeitleiste ergänzt die verknüpften Ereignisse.' },
    review: { title: 'Tausche DOCX-Überarbeitungen aus', description: 'Sende deinem Lektorat ein Dokument und importiere die zurückgegebenen Änderungsvorschläge mit Zuordnung zum Urheber.' },
    comments: { title: 'Behalte Kommentare im Kontext', description: 'Verknüpfe Gespräche mit dem Text und schließe sie ab, während die Überarbeitung vorankommt.' },
    history: { title: 'Vergleiche frühere Fassungen', description: 'Sieh den Szenenverlauf durch, vergleiche frühere Texte und halte benannte Momentaufnahmen einer Fassung fest.' },
    revisions: { title: 'Plane die nächste Runde', description: 'Ordne die Arbeit in Überarbeitungsrunden und Aufgaben, statt eine getrennte Liste neben dem Buch zu führen.' },
    export: { title: 'Wähle ein passendes Format', description: 'Exportiere Markdown, DOCX oder EPUB für den nächsten Schritt mit deinem Buch.' },
    design: { title: 'Bereite das vollständige Buch vor', description: 'Lege Buchdesign, Vor- und Nachspann sowie Cover vor dem Export fest.' },
    authors: { title: 'Schreibe unter einem Pseudonym', description: 'Halte Schreibidentitäten und Veröffentlichungsdetails für dein Buch bereit.' },
    proof: { title: 'Prüfe einen Korrekturabzug', description: 'Unter Linux kannst du das Buchlayout vorab ansehen und vor der Veröffentlichung einen PDF-Korrekturabzug exportieren.' },
    archives: { title: 'Erstelle verschlüsselte Archive', description: 'Erstelle ein Archiv manuell, prüfe es mit deinem Wiederherstellungsschlüssel und stelle es als separates Buch wieder her.' },
    mirror: { title: 'Behalte einen lesbaren Spiegel', description: 'Nutze einen lesbaren Ordner neben deinem Buch. Er ermöglicht Zugriff auf den Text, ist aber keine vollständige Sicherung.' },
    salvage: { title: 'Rette, was sich retten lässt', description: 'Lokale Wiederherstellungskopien, Szenenverlauf und Rettungswerkzeuge bieten verschiedene Wege zurück zu deiner Arbeit.' },
    series: { title: 'Arbeite an einer Reihe', description: 'Ordne Bücher zu einer Reihe, während jedes Manuskript auf deinem eigenen Datenträger bleibt.' },
    reports: { title: 'Verstehe deine Schreibarbeit', description: 'Sieh Buchstatistiken, optionale lokale Sitzungsstatistiken und lokale Berichte zu Schreibhandwerk und Konsistenz.' },
    lock: { title: 'Verbirg die Desktop-App', description: 'Auf unterstützten Desktop-Builds verbirgt die optionale PIN-Sperre die Anwendung, wenn du weggehst. Sie verschlüsselt keine Manuskriptdateien.' },
    formattingAlt: 'Formatierungswerkzeuge neben ausgewähltem Text aus Alice im Wunderland in garret',
    formattingCaption: 'Formatierungswerkzeuge bleiben bei deiner Textauswahl.',
    cardsAlt: 'garret-Gliederungskarten mit Kapiteln, Szenen und Zusammenfassungen',
    cardsCaption: 'Erfasse die Struktur auf einen Blick mit Gliederungskarten.',
    historyAlt: 'garret-Szenenverlauf mit einem Vergleich zwischen einer früheren Fassung und dem aktuellen Text',
    historyCaption: 'Frühere Formulierungen bleiben im Szenenverlauf verfügbar.',
  },
} satisfies Copy;
