export const en = {
  nav: { studio: 'The studio', downloads: 'Downloads', guide: 'Guide', source: 'Source code' },
  mainNavigation: 'Main navigation',
  languageLabel: 'EN, Read in English',
  footerNavigation: 'Further information',
  skip: 'Skip to content',
  home: 'garret home',
  themeToggle: { light: 'Switch to light mode', dark: 'Switch to dark mode' },
  zoom: 'Zoom', fit: 'Fit',
  close: 'Close',
  enlarge: 'View screenshot',
  imageLoading: 'Loading screenshot...',
  imageError: 'The screenshot could not load. Try opening the original image.',
  imageRegion: 'Screenshot, scrollable when zoomed',
  zoomHint: 'Choose Zoom to read the details.',
  panHint: 'Scroll to explore the zoomed image. To use the arrow keys, press Tab until you reach the image.',
  allDownloads: 'See all downloads',
  original: 'Open original image',
  newTab: 'opens in a new tab',
  footer: {
    creator: 'By Iulian Dita',
    about: 'About & privacy', credits: 'Image credits', issues: 'Report a problem',
    support: 'Support garret', license: 'Free software. GPL-3.0-or-later.',
  },
  hero: {
    androidNote: 'The Android app has a library and scene editor, with fewer features than desktop. This version cannot import or export books, make encrypted archives, or sync books automatically. Uninstalling or clearing app data deletes its books.',
    getFor: 'Get garret for {platform}', alpha: 'Early alpha.', alphaGuide: 'Read the guide before using it for important work.',
    title: 'A writing studio for the whole novel.',
    description: 'Your manuscript, characters, research, and revisions in one place. Write offline, without an account. Every feature is free.',
    download: 'Get garret', explore: 'Explore the studio',
    caption: 'The desktop editor. Your manuscript, with the rest of your book within reach.',
    alt: 'garret manuscript editor with chapter navigation and writing tools',
    darkAlt: 'garret editor in dark mode with Dracula and chapter navigation',
  },
  studio: {
    write: { title: 'Make room for the words.', description: 'Write in scenes and chapters. Find a passage across the book, leave a comment, or return to an earlier scene version. Focus mode makes space for the manuscript.' },
    organize: { title: 'Keep the story straight.', description: 'Build your cast and story bible. Keep synopses and research close. Lay out events on a timeline, then follow them back to the scene.', alt: 'Sample Dracula narrative events arranged on the garret timeline', caption: 'A timeline that stays connected to the manuscript.' },
    revise: { title: 'Bring the next draft into focus.', description: 'Exchange DOCX review documents with your editor. See who proposed a change, accept or reject it, and keep comments, revision passes, and tasks with the book.', alt: 'Proposed changes showing who suggested each one beside the manuscript in garret', caption: 'Editorial feedback stays beside the manuscript.' },
    prepare: { title: 'From manuscript to book.', description: 'Export Markdown, DOCX, or EPUB. Set up covers, pen names, front and back matter, and book design. Linux also offers PDF proof copies.', alt: 'Book design and EPUB export controls in garret', caption: 'Prepare an EPUB without leaving your writing studio.' },
  },
  ownership: {
    title: 'Your book stays yours.',
    description: 'Books live on your disk. Write without an internet connection or an account. All features are free, and the source is open.',
    backup: 'Working books are not encrypted. Keep them outside cloud-synced folders. Make encrypted archives manually, keep the recovery key separately, and verify your saved archive.',
    link: 'Keep a safe copy',
  },
  android: {
    download: 'Get garret for Android',
    title: 'A smaller studio for your phone.',
    description: 'Android has a library and scene editor for writing on the go, with fewer features than desktop. This version cannot import or export books, make encrypted archives, or sync books automatically. Uninstalling or clearing app data deletes its books; copy important text into another app as a separate backup.',
    alt: 'Android garret scene editor showing manuscript text',
    darkAlt: 'Android garret scene editor in dark mode showing Dracula',
    caption: 'The Android scene editor.',
  },
  highlights: {
    title: 'Less between you and your novel.',
    write: { title: 'Room to write', description: 'A focused editor, scenes and chapters, and your words saved on your own disk.' },
    story: { title: 'The whole story, together', description: 'Characters, research, and plans stay close to the manuscript, without a pile of separate files.' },
    finish: { title: 'A path to the finished book', description: 'Revise with your editor, shape the book, and export it when you are ready.' },
  },
  testimonial: {
    label: 'A writer\'s first impression',
    attribution: 'George Patterson',
  },
  browse: {
    title: 'More tools, when you need them.',
    description: 'Explore the desktop studio at your own pace.',
    previous: 'Previous topic', next: 'Next topic',
    fallbackHint: 'Choose a topic or swipe.',
    position: 'Topic', of: 'of', hint: 'Choose a topic, use the arrows, or swipe.',
  },
  features: {
    recoveryTitle: 'Keep a way back to your work.',
    region: 'Desktop features',
    navigate: 'Explore desktop features',
    writing: 'Writing', organizing: 'Story & research', revision: 'Revision', publishing: 'Publishing', recovery: 'Ownership & recovery',
    focus: { title: 'Focus on a scene', description: 'Work in parts, chapters, and scenes. Focus mode fades the surrounding tools while you write.' },
    formatting: { title: 'Format as you write', description: 'Keep formatting controls beside your selection, with undo and redo when a sentence needs another pass.' },
    search: { title: 'Search the whole book', description: 'Find a name or phrase across the manuscript and jump back to the passage.' },
    preferences: { title: 'Write your way', description: 'Choose light or dark mode, English or German, and your own daily word goal. Show word counts for scenes, chapters, or parts as you prefer.' },
    cast: { title: 'Know your cast', description: 'Keep character profiles, aliases, pictures, and descriptions beside the manuscript.' },
    bible: { title: 'Keep a story bible', description: 'Give your world, continuity rules, and background notes a home inside the book.' },
    synopses: { title: 'Summarize each scene', description: 'Write scene synopses and read them alongside the manuscript or in the outline.' },
    research: { title: 'Keep research close', description: 'Connect research files to the book so source material stays within reach while you write.' },
    outline: { title: 'See the shape of the story', description: 'Arrange chapters and scenes in an outline table or cards, with their summaries in view.' },
    appearances: { title: 'Follow characters across scenes', description: 'See which scenes each character appears in and follow linked events on the timeline.' },
    review: { title: 'Work with your editor', description: 'Send a DOCX review document to your editor and import their proposed changes. See who suggested each one.' },
    comments: { title: 'Keep comments in context', description: 'Attach editorial conversations to the text and resolve them as the draft moves forward.' },
    history: { title: 'Compare earlier versions', description: 'Review scene history, compare previous text, and keep named snapshots of a draft.' },
    revisions: { title: 'Plan your next revision', description: 'Keep revision tasks with your book and group them into rounds of work.' },
    export: { title: 'Choose a useful format', description: 'Export Markdown, DOCX, or EPUB for the next stage of your book.' },
    design: { title: 'Prepare the complete book', description: 'Set up book design, front and back matter, and covers before export.' },
    authors: { title: 'Write under a pen name', description: 'Keep your pen names and publication details together.' },
    proof: { title: 'Check a proof copy', description: 'On Linux, preview the book layout and export a PDF proof before publishing.' },
    archives: { title: 'Save an encrypted backup', description: 'Make an encrypted archive manually, check it with your recovery key, and restore it as a separate book when you need it.' },
    mirror: { title: 'Keep a readable copy', description: 'Keep your text in a readable folder alongside your book. This copy is unencrypted and is not a complete backup.' },
    salvage: { title: 'Recover what you can', description: 'Local recovery copies, scene history, and salvage tools provide different ways back to your work.' },
    series: { title: 'Work across a series', description: 'Organize books into a series while keeping each manuscript on your own disk.' },
    reports: { title: 'Keep track of your writing', description: 'See statistics for your book and reports on writing and consistency. Session statistics are optional. All of these stay on your device.' },
    lock: { title: 'Hide the app when you step away', description: 'On Linux, an optional PIN lock hides garret when you step away. Your manuscript files remain unencrypted.' },
    formattingAlt: 'Formatting controls beside selected text from Alice’s Adventures in Wonderland in garret',
    formattingCaption: 'Formatting stays beside your selected words.',
    cardsAlt: 'garret outline cards showing chapters, scenes, and summaries',
    cardsCaption: 'Keep story structure and characters beside the manuscript.',
    castAlt: 'garret showing a Dracula character profile beside the manuscript',
    commentsAlt: 'garret with a sample editorial comment beside selected Pride and Prejudice text',
    historyAlt: 'garret scene history comparing an earlier manuscript version with the current text',
    historyCaption: 'Compare earlier words in scene history. Shown here with sample revisions.',
  },
} as const;

export type Copy = {
  [K in keyof typeof en]: typeof en[K] extends string ? string : {
    [P in keyof typeof en[K]]: typeof en[K][P] extends string ? string : {
      [Q in keyof typeof en[K][P]]: string
    }
  }
};
