export const pages = {
  en: {
    downloads: {
      title: 'Choose your writing studio.',
      description: 'Download garret for your device. Every feature is free.',
      alpha: 'Early alpha. Keep a backup of your work before trying a new build.',
      version: 'Current release',
      download: 'Download for',
      suggested: 'Suggested for this device',
      missing: 'A direct download is not available here. Check the release listing for current builds.',
      listing: 'View releases',
      requirements: {
        linux: 'x86_64, glibc 2.39+, WebKitGTK 4.1. Ubuntu 24.04 and Mint 22 are suitable baselines. Install libwebkit2gtk-4.1-0; a Hunspell dictionary is optional.',
        windows: 'x86_64 with Microsoft Edge WebView2. PDF proof, privacy locking, and the single-instance guard are unavailable on Windows.',
        macos: 'Apple Silicon and Intel alpha builds. Native tester feedback is still needed. Choose the architecture that matches your Mac.',
        android: 'APK for arm64 and x86_64. Allow installation from your browser when Android asks. Library and scene editing, with fewer features than desktop. No automatic book sync.',
      },
      instructions: 'Extract the whole desktop package and follow the included README. On Android, install the APK; the release includes a separate instructions ZIP.',
      checksums: 'Release notes, checksums, and Android instructions',
      source: 'Build from source (Linux)',
      backup: 'Read the backup guide before starting',
    },
    guide: {
      title: 'Start with a scene.',
      description: 'Install garret, open a book, and keep a safe copy as you write.',
      install: 'Install your build',
      installText: 'Choose your device on the downloads page. Extract the whole desktop package, keep its files together, and follow the included README. On Android, install the APK and read the Android instructions in the release.',
      book: 'Create or open a book',
      bookText: 'Open garret and use the library to create a new book or open an existing one. Choose a folder on your own disk, outside cloud-synced folders. New books default to Documents/Books until you choose another location.',
      scene: 'Write the first scene',
      sceneText: 'Open your book, add a chapter and a scene, and start writing. Arrange scenes as the story grows. Use the story bible, cast, and research tools when you need them; you can begin with the manuscript alone.',
      backup: 'Keep a safe copy',
      backupText: 'Back up now makes a local recovery copy. It cannot protect your work if you lose the device. Use an encrypted archive for a separate copy on a USB drive or in a synced backup folder.',
      steps: [
        'Open File > Open book > Backups and archives.',
        'Choose Create recovery key. Keep this key separately from your backups. A lost key means you cannot restore an encrypted archive.',
        'Select Choose backup folder, then Make encrypted archive. Save to a USB drive or a cloud-synced backup folder, or copy the archive there afterward.',
        'Use Verify encrypted archive to check the saved archive with your key.',
      ],
      boundaries: 'Creating each archive is manual. Uploading it is handled by your sync client. Your working manuscript is not encrypted, and desktop and Android books do not sync automatically.',
      restore: 'Restore encrypted archive creates a separate book. Open the restored book from the library.',
      files: 'For a file-copy backup, close the app first. Copy the book database together with its adjacent pictures and research folders. A database-only copy is incomplete.',
      next: 'Revise and prepare',
      nextText: 'On desktop, exchange DOCX review documents with an editor and accept or reject attributed proposals. Export Markdown, DOCX, or EPUB; PDF proof copies are available on Linux. Keep a backup before importing changes or moving to a new alpha build.',
    },
    about: {
      title: 'A place for the whole book.',
      description: 'garret is a free, open-source writing studio for novelists.',
      purpose: 'Why garret exists',
      purposeText: 'A novel needs more than a text editor. garret keeps the manuscript, story planning, research, and revisions together, while leaving books on the writer’s own disk. No subscription, account, or paid feature unlocks.',
      privacy: 'Local books. A simple website.',
      privacyText: 'You do not upload manuscripts to this website. It has no analytics scripts, third-party embeds, remote fonts, forms, or accounts. The only preference saved by the site is your theme choice, in this browser.',
      hosting: 'Hosting providers process ordinary web requests, including connection information. Downloads, source code, issue reporting, and optional support links take you to external services with their own privacy practices.',
      appPrivacy: 'garret works offline. Working books are not encrypted. Encrypted archives are separate, manually created backups. The optional desktop PIN lock conceals the app; it does not encrypt manuscript files.',
      license: 'Free software',
      licenseText: 'The application and this website are licensed under GPL-3.0-or-later. You can inspect the source, report problems, and contribute.',
      credits: 'Image credits',
      creditsText: 'Wordmarks and screenshots come from the real garret application. Screenshots contain classic excerpts from Pride and Prejudice, Alice\'s Adventures in Wonderland, and Dracula, with illustrative editorial material. Sample character notes, timelines, reviews, and tasks are examples, not claims about the authors’ working process.',
      gallery: 'Gallery credits and sample sources',
      icons: 'OS symbols are Tabler Icons, licensed under MIT.',
    },
  },
  de: {
    downloads: {
      title: 'Wähle dein Schreibstudio.',
      description: 'Lade garret für dein Gerät herunter. Alle Funktionen sind kostenlos.',
      alpha: 'Frühe Alpha-Version. Sichere deine Arbeit, bevor du eine neue Version ausprobierst.',
      version: 'Aktuelle Version',
      download: 'Download für',
      suggested: 'Für dieses Gerät vorgeschlagen',
      missing: 'Hier ist kein direkter Download verfügbar. Prüfe die aktuellen Builds in der Versionsübersicht.',
      listing: 'Versionen ansehen',
      requirements: {
        linux: 'x86_64, glibc 2.39+, WebKitGTK 4.1. Ubuntu 24.04 und Mint 22 sind geeignete Grundlagen. Installiere libwebkit2gtk-4.1-0; ein Hunspell-Wörterbuch ist optional.',
        windows: 'x86_64 mit Microsoft Edge WebView2. PDF-Korrekturabzüge, die PIN-Sperre und die Beschränkung auf eine laufende Instanz sind unter Windows nicht verfügbar.',
        macos: 'Alpha-Builds für Apple Silicon und Intel. Rückmeldungen von Tests auf echten Macs stehen noch aus. Wähle die Architektur deines Macs.',
        android: 'APK für arm64 und x86_64. Erlaube die Installation aus deinem Browser, wenn Android danach fragt. Bibliothek und Szeneneditor mit weniger Funktionen als auf dem Desktop. Keine automatische Synchronisierung.',
      },
      instructions: 'Entpacke das gesamte Desktop-Paket und folge der enthaltenen README. Installiere unter Android die APK; die Version enthält eine separate ZIP-Datei mit Anleitungen.',
      checksums: 'Versionshinweise, Prüfsummen und Android-Anleitung',
      source: 'Aus dem Quellcode bauen (Linux)',
      backup: 'Lies zuerst die Anleitung zur Sicherung',
    },
    guide: {
      title: 'Beginne mit einer Szene.',
      description: 'Installiere garret, öffne ein Buch und sichere deine Arbeit beim Schreiben.',
      install: 'Installiere deinen Build',
      installText: 'Wähle dein Gerät auf der Downloadseite. Entpacke das gesamte Desktop-Paket, halte seine Dateien zusammen und folge der enthaltenen README. Installiere unter Android die APK und lies die Android-Anleitung der Version.',
      book: 'Erstelle oder öffne ein Buch',
      bookText: 'Öffne garret und erstelle in der Bibliothek ein neues Buch oder öffne ein vorhandenes. Wähle einen Ordner auf deinem eigenen Datenträger, außerhalb von Cloud-Ordnern. Neue Bücher landen standardmäßig in Documents/Books, bis du einen anderen Ort wählst.',
      scene: 'Schreibe die erste Szene',
      sceneText: 'Öffne dein Buch, füge ein Kapitel und eine Szene hinzu und beginne zu schreiben. Ordne die Szenen, während die Geschichte wächst. Nutze Story-Bibel, Figurenkartei und Recherche nach Bedarf; du kannst mit dem Manuskript allein beginnen.',
      backup: 'Behalte eine sichere Kopie',
      backupText: 'Jetzt sichern erstellt eine lokale Wiederherstellungskopie. Sie schützt dich nicht vor dem Verlust des Geräts. Nutze ein verschlüsseltes Archiv für eine getrennte Kopie auf einem USB-Laufwerk oder in einem synchronisierten Sicherungsordner.',
      steps: [
        'Öffne Datei > Buch öffnen > Sicherungen und Archive.',
        'Wähle Wiederherstellungsschlüssel erstellen. Bewahre den Schlüssel getrennt von deinen Sicherungen auf. Ohne ihn kannst du ein verschlüsseltes Archiv nicht wiederherstellen.',
        'Wähle Sicherungsordner wählen und dann Verschlüsseltes Archiv erstellen. Speichere es auf einem USB-Laufwerk oder in einem Cloud-Sicherungsordner, oder kopiere es anschließend dorthin.',
        'Prüfe das gespeicherte Archiv mit deinem Schlüssel über Verschlüsseltes Archiv prüfen.',
      ],
      boundaries: 'Jedes Archiv wird manuell erstellt. Den Upload übernimmt dein Synchronisierungsprogramm. Dein Arbeitsmanuskript ist nicht verschlüsselt. Bücher auf Desktop und Android werden nicht automatisch synchronisiert.',
      restore: 'Verschlüsseltes Archiv wiederherstellen erstellt ein separates Buch. Öffne das wiederhergestellte Buch aus der Bibliothek.',
      files: 'Schließe die App vor einer Dateikopie. Kopiere die Buchdatenbank zusammen mit den danebenliegenden Bilder- und Rechercheordnern. Eine Datenbank allein ist keine vollständige Sicherung.',
      next: 'Überarbeite und bereite das Buch vor',
      nextText: 'Tausche auf dem Desktop DOCX-Dokumente mit einem Lektorat aus und nimm zugeordnete Änderungsvorschläge an oder lehne sie ab. Exportiere Markdown, DOCX oder EPUB; PDF-Korrekturabzüge sind unter Linux verfügbar. Sichere dein Buch vor dem Import von Änderungen oder dem Wechsel auf eine neue Alpha-Version.',
    },
    about: {
      title: 'Ein Platz für das ganze Buch.',
      description: 'garret ist ein kostenloses, quelloffenes Schreibstudio für Romanautoren.',
      purpose: 'Warum es garret gibt',
      purposeText: 'Ein Roman braucht mehr als einen Texteditor. garret hält Manuskript, Planung, Recherche und Überarbeitung zusammen. Die Bücher bleiben auf dem eigenen Datenträger. Ohne Abo, Konto oder kostenpflichtige Freischaltungen.',
      privacy: 'Lokale Bücher. Eine einfache Website.',
      privacyText: 'Du lädst keine Manuskripte auf diese Website hoch. Sie enthält keine Analyseskripte, externen Einbettungen, entfernten Schriftarten, Formulare oder Konten. Nur deine Darstellungswahl wird lokal in diesem Browser gespeichert.',
      hosting: 'Hosting-Anbieter verarbeiten normale Webanfragen einschließlich Verbindungsinformationen. Downloads, Quellcode, Fehlermeldungen und freiwillige Unterstützung führen zu externen Diensten mit eigenen Datenschutzregeln.',
      appPrivacy: 'garret funktioniert offline. Arbeitsbücher sind nicht verschlüsselt. Verschlüsselte Archive sind getrennte, manuell erstellte Sicherungen. Die optionale Desktop-PIN-Sperre verbirgt die App; sie verschlüsselt keine Manuskriptdateien.',
      license: 'Freie Software',
      licenseText: 'Die Anwendung und diese Website stehen unter GPL-3.0-or-later. Du kannst den Quellcode prüfen, Probleme melden und mitarbeiten.',
      credits: 'Bildnachweise',
      creditsText: 'Wortmarken und Screenshots stammen aus der echten garret-Anwendung. Die Bilder zeigen klassische Auszüge aus Stolz und Vorurteil, Alice im Wunderland und Dracula mit beispielhaftem Lektoratsmaterial. Figureninformationen, Zeitleisten, Änderungen und Aufgaben sind Beispiele, keine Aussagen über die Arbeitsweise der Autoren.',
      gallery: 'Galerie-Nachweise und Beispielquellen',
      icons: 'Die Betriebssystem-Symbole stammen aus Tabler Icons und stehen unter der MIT-Lizenz.',
    },
  },
} as const;
