export const pages = {
  en: {
    downloads: {
      title: 'Get garret for your device.',
      description: 'Download garret for your device. Every feature is free.',
      alpha: 'Early alpha. Keep a backup of your work before trying a new version.',
      version: 'Current release',
      download: 'Download garret for {platform}',
      suggested: 'Suggested for this device',
      available: 'You can use garret on Linux, Windows, macOS, and Android. There is no dedicated version for iOS or ChromeOS.',
      downloadArchitecture: 'Download garret for {architecture}',
      missing: 'This download is not available here. Check the release page for current versions.',
      listing: 'View releases',
      requirements: {
        linux: 'For Ubuntu 24.04 and Linux Mint 22 on x86_64 computers. Other distributions need glibc 2.39+ and WebKitGTK 4.1.',
        windows: 'x86_64 with Microsoft Edge WebView2. Extract the complete package and follow its included README.',
        macos: 'Alpha versions for Apple Silicon and Intel. Feedback from Mac users is still needed. In Apple menu > About This Mac, look for an Apple chip or an Intel processor. Choose the matching download.',
        android: 'APK for arm64 and x86_64. Allow installation from your browser when Android asks. Library and scene editing, with fewer features than desktop. No automatic book sync.',
      },
      linuxInstall: 'Install', linuxOptional: '; a Hunspell dictionary is optional.',
      androidLimits: 'No import/export or encrypted archives in this version. Uninstalling or clearing app data deletes local books; Android system backup is disabled.',
      androidGuide: 'Read the Android guide before writing important text.',
      notes: 'Installation notes',
      instructions: 'Extract the whole desktop package and follow the included README. On Android, install the APK; the release includes a separate instructions ZIP.',
      checksums: 'Release notes, checksums, and Android instructions',
      source: 'Build from source (Linux)',
      backup: 'Read the backup guide before starting',
    },
    guide: {
      contents: 'On this page',
      title: 'Start with a scene.',
      description: 'Install garret, open a book, and keep a safe copy as you write.',
      install: 'Install garret',
      installText: 'Choose your device on the downloads page. Extract the whole desktop package, keep its files together, and follow the included README. On Android, install the APK and read the Android instructions in the release.',
      desktop: 'On desktop', android: 'On Android',
      androidIntro: 'The Android app has its own library and scene editor. Use these steps instead of the desktop menus.',
      androidSteps: [
        { action: 'New book > Create book.', detail: 'Enter a book title in the library, then create the book.' },
        { action: 'Outline > Scene title > Add scene.', detail: 'Enter a scene title, add it, and start writing.' },
        { action: 'Saved on this device.', detail: 'Wait for this message before closing the app. Open the book again to continue.' },
      ],
      androidLimits: 'This Android version has no import/export, encrypted archives, or automatic sync. Uninstalling the app or clearing its data deletes its local books; Android platform backup is disabled. Try it with practice text, or keep an independent copy of anything important.',
      androidInstructions: 'Download the Android instructions (ZIP)',
      book: 'Create or open a book',
      bookText: 'Open garret and use the library to create a new book or open an existing one. Choose a folder on your own disk, outside cloud-synced folders. New books default to Documents/Books until you choose another location. Check whether Documents is synced by OneDrive, iCloud, or another service; if it is, choose a different local folder.',
      scene: 'Write the first scene',
      sceneText: 'Open your book, add a chapter and a scene, and start writing. Arrange scenes as the story grows. Use the story bible, cast, and research tools when you need them; you can begin with the manuscript alone.',
      backup: 'Keep a safe copy',
      backupCommand: 'Back up now',
      backupText: 'makes a local recovery copy. It cannot protect your work if you lose the device. Use an encrypted archive for a separate copy on a USB drive or in a synced backup folder.',
      steps: [
        { action: 'File > Open book > Backups and archives.', detail: 'Open this section in the app.' },
        { action: 'Create recovery key.', detail: 'Keep this key separately from your backups. A lost key means you cannot restore an encrypted archive.' },
        { action: 'Choose backup folder, then Make encrypted archive.', detail: 'Save to a USB drive or a cloud-synced backup folder, or copy the archive there afterward.' },
        { action: 'Verify encrypted archive.', detail: 'Check the saved archive with your key.' },
      ],
      boundaries: 'Creating each archive is manual. Uploading it is handled by your sync client. Your working manuscript is not encrypted, and desktop and Android books do not sync automatically.',
      restoreCommand: 'Restore encrypted archive',
      restore: 'creates a separate book. Open the restored book from the library.',
      files: 'For a file-copy backup, close the app first. Copy the book database together with its adjacent pictures and research folders. A database-only copy is incomplete. This file-copy backup is not encrypted.',
      next: 'Revise and prepare',
      nextText: 'On desktop, exchange DOCX review documents with an editor, see who suggested each change, and accept or reject their proposals. Export Markdown, DOCX, or EPUB; PDF proof copies are available on Linux. Keep a backup before importing changes or moving to a new alpha version.',
    },
    about: {
      contents: 'On this page',
      title: 'About garret.',
      description: 'Meet garret, a free writing studio for novelists, and learn about privacy in the app and on this website.',
      purpose: 'Why garret exists',
      purposeText: 'garret brings your manuscript, story planning, research, and revisions together. Your books stay on your own device. No subscription, no account, and no paid features.',
      privacy: 'Privacy and website analytics',
      privacyText: 'You do not upload manuscripts to this website. We use Cloudflare Web Analytics to measure website visits, page views, and referring sites without analytics cookies. Google Search Console reports how this site appears in Google Search; it adds no tracking script to the website. Your theme choice is saved only in this browser.',
      analyticsLink: 'How Cloudflare Web Analytics works',
      hosting: 'Hosting providers process ordinary web requests, including connection information. Downloads, source code, issue reporting, and optional support links take you to external services with their own privacy practices.',
      appPrivacy: 'garret works offline. Working books are not encrypted. Encrypted archives are separate, manually created backups. The optional desktop PIN lock conceals the app; it does not encrypt manuscript files.',
      license: 'Free software',
      licenseText: 'The application and this website are licensed under GPL-3.0-or-later. You can inspect the source, report problems, and contribute.',
      credits: 'Image credits',
      creditsText: 'Wordmarks and screenshots come from the real garret application. Screenshots contain classic excerpts from Pride and Prejudice, Alice’s Adventures in Wonderland, and Dracula, with illustrative editorial material. Sample character notes, timelines, reviews, and tasks are examples, not claims about the authors’ working process.',
      illustrationCredits: 'The notebook and attic-window illustrations are AI-generated decorative artwork made for this website and included under its GPL-3.0-or-later license.',
      gallery: 'Gallery credits and sample sources',
      appSource: 'Application source', siteSource: 'Website source', iconLicense: 'MIT license',
      icons: 'OS symbols are Tabler Icons.',
    },
  },
  de: {
    downloads: {
      title: 'Hol dir garret für dein Gerät.',
      description: 'Lade garret für dein Gerät herunter. Alle Funktionen sind kostenlos.',
      alpha: 'Frühe Alpha-Version. Sichere deine Arbeit, bevor du eine neue Version ausprobierst.',
      version: 'Aktuelle Version',
      download: 'garret für {platform} laden',
      suggested: 'Für dieses Gerät vorgeschlagen',
      available: 'Du kannst garret auf Linux, Windows, macOS und Android nutzen. Für iOS und ChromeOS gibt es keine eigene Version.',
      downloadArchitecture: 'garret für {architecture} laden',
      missing: 'Hier ist kein direkter Download verfügbar. Aktuelle Downloads findest du in der Versionsübersicht.',
      listing: 'Versionen ansehen',
      requirements: {
        linux: 'Für Ubuntu 24.04 und Linux Mint 22 auf x86_64-Computern. Andere Distributionen benötigen glibc 2.39+ und WebKitGTK 4.1.',
        windows: 'x86_64 mit Microsoft Edge WebView2. Entpacke das vollständige Paket und folge der enthaltenen README.',
        macos: 'Alpha-Versionen für Apple Silicon und Intel. Rückmeldungen zur Nutzung auf dem Mac stehen noch aus. Unter Apple-Menü > Über diesen Mac findest du den Apple-Chip oder Intel-Prozessor. Wähle den passenden Download.',
        android: 'APK für arm64 und x86_64. Erlaube die Installation aus deinem Browser, wenn Android danach fragt. Bibliothek und Szeneneditor mit weniger Funktionen als auf dem Desktop. Keine automatische Synchronisierung.',
      },
      linuxInstall: 'Installiere', linuxOptional: '; ein Hunspell-Wörterbuch ist optional.',
      androidLimits: 'Diese Version hat keinen Import oder Export und keine verschlüsselten Archive. Beim Deinstallieren oder Löschen der App-Daten gehen lokale Bücher verloren; Android-Systemsicherungen sind deaktiviert.',
      androidGuide: 'Lies die Android-Anleitung, bevor du wichtige Texte schreibst.',
      notes: 'Installationshinweise',
      instructions: 'Entpacke das gesamte Desktop-Paket und folge der enthaltenen README. Installiere unter Android die APK; die Version enthält eine separate ZIP-Datei mit Anleitungen.',
      checksums: 'Versionshinweise, Prüfsummen und Android-Anleitung',
      source: 'Aus dem Quellcode bauen (Linux)',
      backup: 'Lies zuerst die Anleitung zur Sicherung',
    },
    guide: {
      contents: 'Auf dieser Seite',
      title: 'Beginne mit einer Szene.',
      description: 'Installiere garret, öffne ein Buch und sichere deine Arbeit beim Schreiben.',
      install: 'Installiere garret',
      installText: 'Wähle dein Gerät auf der Downloadseite. Entpacke das gesamte Desktop-Paket, halte seine Dateien zusammen und folge der enthaltenen README. Installiere unter Android die APK und lies die Android-Anleitung der Version.',
      desktop: 'Auf dem Desktop', android: 'Auf Android',
      androidIntro: 'Die Android-App hat eine eigene Bibliothek und einen Szeneneditor. Nutze diese Schritte statt der Desktop-Menüs.',
      androidSteps: [
        { action: 'Neues Buch > Buch erstellen.', detail: 'Gib in der Bibliothek einen Buchtitel ein und erstelle das Buch.' },
        { action: 'Gliederung > Szenentitel > Szene hinzufügen.', detail: 'Gib einen Szenentitel ein, füge die Szene hinzu und beginne zu schreiben.' },
        { action: 'Auf diesem Gerät gespeichert.', detail: 'Warte vor dem Schließen auf diese Meldung. Öffne das Buch später erneut, um weiterzuschreiben.' },
      ],
      androidLimits: 'Diese Android-Version bietet keinen Import oder Export, keine verschlüsselten Archive und keine automatische Synchronisierung. Beim Deinstallieren oder Löschen der App-Daten gehen die lokalen Bücher verloren; Android-Systemsicherungen sind deaktiviert. Probiere es mit Übungstexten aus oder bewahre eine unabhängige Kopie wichtiger Texte auf.',
      androidInstructions: 'Android-Anleitung herunterladen (ZIP)',
      book: 'Erstelle oder öffne ein Buch',
      bookText: 'Öffne garret und erstelle in der Bibliothek ein neues Buch oder öffne ein vorhandenes. Wähle einen Ordner auf deinem eigenen Datenträger, außerhalb von Cloud-Ordnern. Neue Bücher landen standardmäßig in Documents/Books, bis du einen anderen Ort wählst. Prüfe, ob Documents von OneDrive, iCloud oder einem anderen Dienst synchronisiert wird; wähle dann einen anderen lokalen Ordner.',
      scene: 'Schreibe die erste Szene',
      sceneText: 'Öffne dein Buch, füge ein Kapitel und eine Szene hinzu und beginne zu schreiben. Ordne die Szenen, während die Geschichte wächst. Nutze Story-Bibel, Figurenkartei und Recherche nach Bedarf; du kannst mit dem Manuskript allein beginnen.',
      backup: 'Lege eine Sicherungskopie an',
      backupCommand: 'Jetzt sichern',
      backupText: 'erstellt eine lokale Wiederherstellungskopie. Sie schützt deine Arbeit nicht, wenn du das Gerät verlierst. Nutze ein verschlüsseltes Archiv für eine getrennte Kopie auf einem USB-Laufwerk oder in einem synchronisierten Sicherungsordner.',
      steps: [
        { action: 'Datei > Buch öffnen > Sicherungen und Archive.', detail: 'Öffne diesen Bereich in der App.' },
        { action: 'Wiederherstellungsschlüssel erstellen.', detail: 'Bewahre den Schlüssel getrennt von deinen Sicherungen auf. Ohne ihn kannst du ein verschlüsseltes Archiv nicht wiederherstellen.' },
        { action: 'Sicherungsordner wählen, dann Verschlüsseltes Archiv erstellen.', detail: 'Speichere es auf einem USB-Laufwerk oder in einem Cloud-Sicherungsordner, oder kopiere es anschließend dorthin.' },
        { action: 'Verschlüsseltes Archiv prüfen.', detail: 'Prüfe das gespeicherte Archiv mit deinem Schlüssel.' },
      ],
      boundaries: 'Jedes Archiv wird manuell erstellt. Den Upload übernimmt dein Synchronisierungsprogramm. Dein Arbeitsmanuskript ist nicht verschlüsselt. Bücher auf Desktop und Android werden nicht automatisch synchronisiert.',
      restoreCommand: 'Verschlüsseltes Archiv wiederherstellen',
      restore: 'erstellt ein separates Buch. Öffne das wiederhergestellte Buch aus der Bibliothek.',
      files: 'Schließe die App vor einer Dateikopie. Kopiere die Buchdatenbank zusammen mit den danebenliegenden Bilder- und Rechercheordnern. Eine Datenbank allein ist keine vollständige Sicherung. Diese Dateikopie ist nicht verschlüsselt.',
      next: 'Überarbeite und bereite das Buch vor',
      nextText: 'Tausche auf dem Desktop DOCX-Dokumente mit einem Lektorat aus. Du siehst, von wem jeder Vorschlag stammt, und kannst ihn annehmen oder ablehnen. Exportiere Markdown, DOCX oder EPUB; PDF-Korrekturabzüge sind unter Linux verfügbar. Sichere dein Buch vor dem Import von Änderungen oder dem Wechsel auf eine neue Alpha-Version.',
    },
    about: {
      contents: 'Auf dieser Seite',
      title: 'Über garret.',
      description: 'Lerne garret kennen, ein kostenloses Schreibstudio für alle, die Romane schreiben, und erfahre mehr zum Datenschutz in der App und auf dieser Website.',
      purpose: 'Warum es garret gibt',
      purposeText: 'garret bringt dein Manuskript, Planung, Recherche und Überarbeitung zusammen. Deine Bücher bleiben auf deinem eigenen Gerät. Ohne Abo, Konto oder kostenpflichtige Funktionen.',
      privacy: 'Datenschutz und Website-Statistik',
      privacyText: 'Du lädst keine Manuskripte auf diese Website hoch. Wir nutzen Cloudflare Web Analytics, um Websitebesuche, Seitenaufrufe und verweisende Websites ohne Analyse-Cookies zu erfassen. Google Search Console zeigt, wie diese Website in der Google-Suche erscheint; dafür wird kein Tracking-Skript auf der Website eingebunden. Deine Wahl des hellen oder dunklen Modus wird nur in diesem Browser gespeichert.',
      analyticsLink: 'So funktioniert Cloudflare Web Analytics',
      hosting: 'Hosting-Anbieter verarbeiten normale Webanfragen einschließlich Verbindungsinformationen. Downloads, Quellcode, Problemmeldungen und freiwillige Unterstützung führen zu externen Diensten mit eigenen Datenschutzregeln.',
      appPrivacy: 'garret funktioniert offline. Arbeitsmanuskripte sind nicht verschlüsselt. Verschlüsselte Archive sind getrennte, manuell erstellte Sicherungen. Die optionale Desktop-PIN-Sperre verbirgt die App; sie verschlüsselt keine Manuskriptdateien.',
      license: 'Freie Software',
      licenseText: 'Die Anwendung und diese Website stehen unter GPL-3.0-or-later. Du kannst den Quellcode prüfen, Probleme melden und mitarbeiten.',
      credits: 'Bildnachweise',
      creditsText: 'Wortmarken und Screenshots stammen aus der echten garret-Anwendung. Die Bilder zeigen klassische Auszüge aus Stolz und Vorurteil, Alice im Wunderland und Dracula mit beispielhaftem Lektoratsmaterial. Figureninformationen, Zeitleisten, Lektoratsvorschläge und Aufgaben sind Beispiele, keine Aussagen darüber, wie diese Bücher entstanden sind. Die Screenshots zeigen die englische Oberfläche; garret ist auch auf Deutsch verfügbar.',
      illustrationCredits: 'Die Notizbuch- und Dachfensterillustrationen sind KI-generierte Dekorationen für diese Website und stehen unter der GPL-3.0-or-later-Lizenz dieser Website.',
      gallery: 'Galerie-Nachweise und Beispielquellen',
      appSource: 'Quellcode der Anwendung', siteSource: 'Quellcode der Website', iconLicense: 'MIT-Lizenz',
      icons: 'Die Betriebssystem-Symbole stammen aus Tabler Icons.',
    },
  },
} as const;
